config/routes.rb
Rails.application.routes.draw do
  resources :contacts do 
    resources :phones
  end
  
  root to: "contacts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    has_many :phones, dependent: :destroy
    validates :firstName, presence: true
    validates :lastName, presence: true
end

app/models/phone.rb
class Phone < ApplicationRecord
    belongs_to :contact
    validates :phoneNumber, presence: true
    validates :category, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName, :email, :address, :site, :description)
    end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]
  before_action :set_contact, only: %i[ show edit index new create update destroy ]  

  # GET /phones or /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @phone = Phone.new(phone_params)
    respond_to do |format|
      if @phone.save
        puts @phone.id
        format.html { redirect_to contact_url(@contact), notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update phone_params
        format.html { redirect_to contact_url(@contact), notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to contact_url(@contact), notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      allowed = params.require(:phone).permit(:phoneNumber, :category)
      allowed[:contact_id] = params[:contact_id]
      allowed
    end

    def set_contact 
      @contact = Contact.find_by(id: params[:contact_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <% if @contact.persisted? %>
    <% @contact.phones.each do |phone| %>
      <div>
        <div>
          <%= phone.category%>:
          <%= phone.phoneNumber%>
        </div>
        <div>
          <%= link_to 'Edit', edit_contact_phone_path(@contact, phone) %>
          <%= link_to 'Destroy', contact_phone_path(@contact, phone), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>
    <div>
      <%= link_to 'New Phone', new_contact_phone_path(@contact) %>
    </div>
  <% end %>
  <% unless @contact.persisted? %>
    <div class="field">
      <%= form.label :phoneNumber %>
      <%= form.text_field :phoneNumber %>
    </div>
    <div class="field">
      <%= form.label :category %>
      <%= form.text_field :category %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contact_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>
<ul>
  <% @contacts.each do |contact| %>
    <li><%=link_to  "#{contact.firstName} #{contact.lastName}" , contact %></li>
  <% end%>
</ul>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.firstName %> <%= @contact.lastName %>
</p>

<%@contact.phones.each do |phone|%>

  <p>
    <strong><%= phone.category %>: </strong>
    <%= phone.phoneNumber %>
  </p>

<% end %>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Site:</strong>
  <%= @contact.site %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %> |
<%= link_to 'Delete', @contact, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phones/_form.html.erb
<%= form_with(model: phone, url: [@contact, phone], local: true) do |form| %>
  <% if phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phoneNumber %>
    <%= form.text_field :phoneNumber %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, value: "Cell phone" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', contact_phone_path(@contact, @phone) %> |
<%= link_to 'Back', contact_phones_path(@contact) %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phones</h1>

<table>
  <thead>
    <tr>
      <th>Phonenumber</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.phoneNumber %></td>
        <td><%= phone.category %></td>        
        <td><%= link_to 'Show', contact_phone_path(@contact, phone) %></td>
        <td><%= link_to 'Edit', edit_contact_phone_path(@contact, phone) %> </td>
        <td><%= link_to 'Destroy', contact_phone_path(@contact, phone), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_contact_phone_path %>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', contact_phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phonenumber:</strong>
  <%= @phone.phoneNumber %>
</p>

<p>
  <strong>Category:</strong>
  <%= @phone.category %>
</p>

<%= link_to 'Edit', edit_contact_phone_path(@contact, @phone) %> |
<%= link_to 'Back', contact_phones_path(@contact) %>